backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "team" # Used in routes, e.g., /admin/collections/blog
    label: "Team Mambers" # Used in the UI
    folder: "_pages/team/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "member"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"} 
      - {label: "Education", name: "education", widget: "string"}
      
