backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "team" # Used in routes, e.g., /admin/collections/blog
    label: "Lab Members" # Used in the UI
    label_singular: "Lab Member"
    folder: "_pages/team/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "member" } 
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", allow_multiple: false, required: false} 
      - { label: "Role", name: "role", widget: "string", required: false}
      - { label: "Permalink", name: "permalink", widget: "string" } 
      - { label: "Education", name: "education", widget: "string", required: false}
      - { label: "Body", name: "body", widget: "markdown", hint: "Main content goes here.", required: false}
      -   label: "Socials"
          name: "social"
          widget: "object"
          summary: '{{fields.website}}: {{fields.github}}'
          fields:
            - {label: "Twitter", name: "twitter", widget: "string", required: false}
            - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
            - {label: "Google Scholar", name: "google-scholar", widget: "string", required: false}
            - {label: "GitHub", name: "github", widget: "string", required: false}
            - {label: "Website", name: "website", widget: "string", required: false}
            - {label: "ORCID", name: "orcid", widget: "string", required: false}
  - name: "news"
    label: "News" 
    label_singular: "Update"
    folder: "_pages/news/_posts"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Category", name: "category", widget: "hidden", default: "update" }
      - { label: "Date", name: "date", widget: "datetime", required: true} 
      - { label: "Title", name: "title", widget: "string", required: true} 
      - { label: "Tags", name: "tags", widget: "list", required: false } 
      - { label: "Body", name: "body", widget: "markdown", hint: "Main article content goes here.", required: false } 
        
      
